export const SEND_REQUEST = 'SEND_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const GET_REQUEST ="GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";

export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const ACCEPT_REQUEST_SUCCESS = 'ACCEPT_REQUEST';
export const ACCEPT_REQUEST_FAILURE= 'ACCEPT_REQUEST';
export const REJECT_REQUEST = 'REJECT_REQUEST';
export const REJECT_REQUEST_SUCCESS = 'REJECT_REQUEST';
export const REJECT_REQUEST_FAILURE = 'REJECT_REQUEST';


export const GET_EDUCATION_DATA = 'GET_EDUCATION_DATA';
export const GET_EDUCATION_DATA_SUCCESS = 'GET_EDUCATION_DATA_SUCCESS';
export const GET_EDUCATION_DATA_FAILURE = 'GET_EDUCATION_DATA_FAILURE';


export const GET_ADDRESS_DATA = 'GET_ADDRESS_DATA';
export const GET_ADDRESS_DATA_SUCCESS = 'GET_ADDRESS_DATA_SUCCESS';
export const GET_ADDRESS_DATA_FAILURE = 'GET_ADDRESS_DATA_FAILURE';

export const GET_PROFESSIONAL_DATA = 'GET_PROFESSIONAL_DATA';
export const GET_PROFESSIONAL_DATA_SUCCESS = 'GET_PROFESSIONAL_DATA_SUCCESS';
export const GET_PROFESSIONAL_DATA_FAILURE = 'GET_PROFESSIONAL_DATA_FAILURE';

export const GET_SENTREQUEST_DATA = 'GET_SENTREQUEST_DATA';
export const GET_SENTREQUEST_DATA_SUCCESS = 'GET_SENTREQUEST_DATA_SUCCESS';
export const GET_SENTREQUEST_DATA_FAILURE = 'GET_SENTREQUEST_DATA_FAILURE';

export const GET_PARTNERPREFERENCE_DATA = 'GET_PARTNERPREFERENCE_DATA';
export const GET_PARTNERPREFERENCE_DATA_SUCCESS = 'GET_PARTNERPREFERENCE_DATA_SUCCESS';
export const GET_PARTNERPREFERENCE_DATA_FAILURE = 'GET_PARTNERPREFERENCE_DATA_FAILURE';

export const GET_ACCEPTED_REQUEST_DATA = "GET_ACCEPTED_REQUEST_DATA"; 
export const GET_ACCEPTED_REQUEST_DATA_SUCCESS = "GET_ACCEPTED_REQUEST_DATA_SUCCESS"; 
export const GET_ACCEPTED_REQUEST_DATA_FAILURE = "GET_ACCEPTED_REQUEST_DATA_FAILURE"; 

export const UPDATE_EDUCATION_DATA = 'UPDATE_EDUCATION_DATA';
export const UPDATE_EDUCATION_DATA_SUCCESS = 'UPDATE_EDUCATION_DATA_SUCCESS';
export const UPDATE_EDUCATION_DATA_FAILURE = 'UPDATE_EDUCATION_DATA_FAILURE';


export const UPDATE_ADDRESS_DATA = 'UPDATE_ADDRESS_DATA';
export const UPDATE_ADDRESS_DATA_SUCCESS = 'UPDATE_ADDRESS_DATA_SUCCESS';
export const UPDATE_ADDRESS_DATA_FAILURE = 'UPDATE_ADDRESS_DATA_FAILURE';

export const UPDATE_PROFESSIONAL_DATA = 'UPDATE_PROFESSIONAL_DATA';
export const UPDATE_PROFESSIONAL_DATA_SUCCESS = 'UPDATE_PROFESSIONAL_DATA_SUCCESS';
export const UPDATE_PROFESSIONAL_DATA_FAILURE = 'UPDATE_PROFESSIONAL_DATA_FAILURE';

export const UPDATE_PARTNERPREFERENCE_DATA = 'UPDATE_PARTNERPREFERENCE_DATA';
export const UPDATE_PARTNERPREFERENCE_DATA_SUCCESS = 'UPDATE_PARTNERPREFERENCE_DATA_SUCCESS';
export const UPDATE_PARTNERPREFERENCE_DATA_FAILURE = 'UPDATE_PARTNERPREFERENCE_DATA_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'

export const GET_BLOCK_USERDATA = 'GET_BLOCK_USERDATA'
export const GET_BLOCK_USERDATA_SUCCESS = 'GET_BLOCK_USERDATA_SUCCESS'
export const GET_BLOCK_USERDATA_FAILURE = 'GET_BLOCK_USERDATA_FAILURE'

export const SENT_BLOCK_REQUEST = "SENT_BLOCK_REQUEST"
export const SENT_BLOCK_REQUEST_SUCCESS = "SENT_BLOCK_REQUEST_SUCCESS"
export const SENT_BLOCK_REQUEST_FAILURE = "SENT_BLOCK_REQUEST_FAILURE"

export const CANCEL_FRIEND_REQUEST = "CANCEL_FRIEND_REQUEST"
export const CANCEL_FRIEND_REQUEST_SUCCESS = "CANCEL_FRIEND_REQUEST_SUCCESS"
export const CANCEL_FRIEND_REQUEST_FAILURE = "CANCEL_FRIEND_REQUEST_FAILURE"