export const SEND_REQUEST = 'SEND_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";

export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const ACCEPT_REQUEST_SUCCESS = 'ACCEPT_REQUEST';
export const ACCEPT_REQUEST_FAILURE = 'ACCEPT_REQUEST';
export const REJECT_REQUEST = 'REJECT_REQUEST';
export const REJECT_REQUEST_SUCCESS = 'REJECT_REQUEST';
export const REJECT_REQUEST_FAILURE = 'REJECT_REQUEST';


export const GET_EDUCATION_DATA = 'GET_EDUCATION_DATA';
export const GET_EDUCATION_DATA_SUCCESS = 'GET_EDUCATION_DATA_SUCCESS';
export const GET_EDUCATION_DATA_FAILURE = 'GET_EDUCATION_DATA_FAILURE';


export const GET_ADDRESS_DATA = 'GET_ADDRESS_DATA';
export const GET_ADDRESS_DATA_SUCCESS = 'GET_ADDRESS_DATA_SUCCESS';
export const GET_ADDRESS_DATA_FAILURE = 'GET_ADDRESS_DATA_FAILURE';

export const GET_PROFESSIONAL_DATA = 'GET_PROFESSIONAL_DATA';
export const GET_PROFESSIONAL_DATA_SUCCESS = 'GET_PROFESSIONAL_DATA_SUCCESS';
export const GET_PROFESSIONAL_DATA_FAILURE = 'GET_PROFESSIONAL_DATA_FAILURE';

export const GET_SENTREQUEST_DATA = 'GET_SENTREQUEST_DATA';
export const GET_SENTREQUEST_DATA_SUCCESS = 'GET_SENTREQUEST_DATA_SUCCESS';
export const GET_SENTREQUEST_DATA_FAILURE = 'GET_SENTREQUEST_DATA_FAILURE';

export const GET_PARTNERPREFERENCE_DATA = 'GET_PARTNERPREFERENCE_DATA';
export const GET_PARTNERPREFERENCE_DATA_SUCCESS = 'GET_PARTNERPREFERENCE_DATA_SUCCESS';
export const GET_PARTNERPREFERENCE_DATA_FAILURE = 'GET_PARTNERPREFERENCE_DATA_FAILURE';

export const GET_ACCEPTED_REQUEST_DATA = "GET_ACCEPTED_REQUEST_DATA";
export const GET_ACCEPTED_REQUEST_DATA_SUCCESS = "GET_ACCEPTED_REQUEST_DATA_SUCCESS";
export const GET_ACCEPTED_REQUEST_DATA_FAILURE = "GET_ACCEPTED_REQUEST_DATA_FAILURE";

export const UPDATE_EDUCATION_DATA = 'UPDATE_EDUCATION_DATA';
export const UPDATE_EDUCATION_DATA_SUCCESS = 'UPDATE_EDUCATION_DATA_SUCCESS';
export const UPDATE_EDUCATION_DATA_FAILURE = 'UPDATE_EDUCATION_DATA_FAILURE';


export const UPDATE_ADDRESS_DATA = 'UPDATE_ADDRESS_DATA';
export const UPDATE_ADDRESS_DATA_SUCCESS = 'UPDATE_ADDRESS_DATA_SUCCESS';
export const UPDATE_ADDRESS_DATA_FAILURE = 'UPDATE_ADDRESS_DATA_FAILURE';

export const UPDATE_PROFESSIONAL_DATA = 'UPDATE_PROFESSIONAL_DATA';
export const UPDATE_PROFESSIONAL_DATA_SUCCESS = 'UPDATE_PROFESSIONAL_DATA_SUCCESS';
export const UPDATE_PROFESSIONAL_DATA_FAILURE = 'UPDATE_PROFESSIONAL_DATA_FAILURE';

export const UPDATE_PARTNERPREFERENCE_DATA = 'UPDATE_PARTNERPREFERENCE_DATA';
export const UPDATE_PARTNERPREFERENCE_DATA_SUCCESS = 'UPDATE_PARTNERPREFERENCE_DATA_SUCCESS';
export const UPDATE_PARTNERPREFERENCE_DATA_FAILURE = 'UPDATE_PARTNERPREFERENCE_DATA_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'

export const GET_BLOCK_USERDATA = 'GET_BLOCK_USERDATA'
export const GET_BLOCK_USERDATA_SUCCESS = 'GET_BLOCK_USERDATA_SUCCESS'
export const GET_BLOCK_USERDATA_FAILURE = 'GET_BLOCK_USERDATA_FAILURE'

export const SENT_BLOCK_REQUEST = "SENT_BLOCK_REQUEST"
export const SENT_BLOCK_REQUEST_SUCCESS = "SENT_BLOCK_REQUEST_SUCCESS"
export const SENT_BLOCK_REQUEST_FAILURE = "SENT_BLOCK_REQUEST_FAILURE"

export const CANCEL_FRIEND_REQUEST = "CANCEL_FRIEND_REQUEST"
export const CANCEL_FRIEND_REQUEST_SUCCESS = "CANCEL_FRIEND_REQUEST_SUCCESS"
export const CANCEL_FRIEND_REQUEST_FAILURE = "CANCEL_FRIEND_REQUEST_FAILURE"

export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE"
export const UPDATE_PROFILE_IMAGE_SUCCESS = "UPDATE_PROFILE_IMAGE_SUCCESS"
export const UPDATE_PROFILE_IMAGE_FAILURE = "UPDATE_PROFILE_IMAGE_FAILURE"
export const UPDATE_PROFILE_IMAGE_PROCESS = "UPDATE_PROFILE_IMAGE_PROCESS"


export const GET_CANCELREQUEST_DATA = "GET_CANCELREQUEST_DATA"
export const GET_CANCELREQUEST_DATA_SUCCESS = "GET_CANCELREQUEST_DATA_SUCCESS"
export const GET_CANCELREQUEST_DATA_FAILURE = "GET_CANCELREQUEST_DATA_FAILURE"

export const DELETE_IMAGE = "DELETE_IMAGE"
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS"
export const DELETE_IMAGE_FAILURE = "DELETE_IMAGE_FAILURE"

export const POST_RECENT_USERPROFILE = "POST_RECENT_USERPROFILE"
export const POST_RECENT_USERPROFILE_SUCCESS = "POST_RECENT_USERPROFILE_SUCCESS"
export const POST_RECENT_USERPROFILE_FAILURE = "POST_RECENT_USERPROFILE_FAILURE"

export const GET_RECENT_USERPROFILE_DATA = "GET_RECENT_USERPROFILE_DATA"
export const GET_RECENT_USERPROFILE_DATA_SUCCESS = "GET_RECENT_USERPROFILE_DATA_SUCCESS"
export const GET_RECENT_USERPROFILE_DATA_FAILURE = "GET_RECENT_USERPROFILE_DATA_FAILURE"


export const GET_SEARCHUSERS_DATA = "GET_SEARCHUSERS_DATA";
export const GET_SEARCHUSERS_DATA_SUCCESS = "GET_SEARCHUSERS_DATA_SUCCESS";
export const GET_SEARCHUSERS_DATA_FAILURE = "GET_SEARCHUSERS_DATA_FAILURE";

export const HIDE_MY_PROFILE = "HIDE_MY_PROFILE";
export const HIDE_MY_PROFILE_SUCCESS = "HIDE_MY_PROFILE_SUCCESS";
export const HIDE_MY_PROFILE_FAILURE = "HIDE_MY_PROFILE_FAILURE";
export const HIDE_MY_PROFILE_CLOSEMODAL = "HIDE_MY_PROFILE_CLOSEMODAL"

export const GET_PRIVACY_QUESTIONS = "GET_PRIVACY_QUESTIONS"
export const GET_PRIVACY_QUESTIONS_SUCCESS = "GET_PRIVACY_QUESTIONS_SUCCESS"
export const GET_PRIVACY_QUESTIONS_FAILURE = "GET_PRIVACY_QUESTIONS_FAILURE"


export const UPDATE_PRIVACY_QUESTIONS = "UPDATE_PRIVACY_QUESTIONS"
export const UPDATE_PRIVACY_QUESTIONS_SUCCESS = "UPDATE_PRIVACY_QUESTIONS_SUCCESS"
export const UPDATE_PRIVACY_QUESTIONS_FAILURE = "UPDATE_PRIVACY_QUESTIONS_FAILURE"


export const FETCH_GRID_USER_DATA_REQUEST = "FETCH_GRID_USER_DATA_REQUEST"
export const FETCH_GRID_USER_DATA_REQUEST_SUCCESS = "FETCH_GRID_USER_DATA_REQUEST_SUCCESS"
export const FETCH_GRID_USER_DATA_REQUEST_FAILURE = "FETCH_GRID_USER_DATA_REQUEST_FAILURE"

export const LIKED_USERS_PROFILE_DATA = "LIKED_USERS_PROFILE_DATA"
export const LIKED_USERS_PROFILE_DATA_SUCCESS = "LIKED_USERS_PROFILE_DATA_SUCCESS"
export const LIKED_USERS_PROFILE_DATA_FAILURE = "LIKED_USERS_PROFILE_DATA_FAILURE"

export const UPLOAD_MY_STORY = "UPLOAD_MY_STORY";
export const UPLOAD_MY_STORY_SUCCESS = "UPLOAD_MY_STORY_SUCCESS";
export const UPLOAD_MY_STORY_FAILURE = "UPLOAD_MY_STORY_FAILURE";
export const UPLOAD_MY_STORY_MODAL = "UPLOAD_MY_STORY_MODAL"

export const GET_ALL_STATUS = "GET_ALL_STATUS";
export const GET_ALL_STATUS_SUCCESS = "GET_ALL_STATUS_SUCCESS";
export const GET_ALL_STATUS_FAILURE = "GET_ALL_STATUS_FAILURE";

export const DELETE_MY_STATUS = "DELETE_MY_STATUS"
export const DELETE_MY_STATUS_SUCCESS = "DELETE_MY_STATUS_SUCCESS"
export const DELETE_MY_STATUS_FAILURE = "DELETE_MY_STATUS_FAILURE"
export const DELETE_STATUS_MODAL = "DELETE_STATUS_MODAL"

export const FETCH_SAFETY_CONSENT_REQUEST = 'FETCH_SAFETY_CONSENT_REQUEST';
export const FETCH_SAFETY_CONSENT_SUCCESS = 'FETCH_SAFETY_CONSENT_SUCCESS';
export const FETCH_SAFETY_CONSENT_FAILURE = 'FETCH_SAFETY_CONSENT_FAILURE';

export const POST_SAFETY_CONSENT_REQUEST = 'POST_SAFETY_CONSENT_REQUEST';
export const POST_SAFETY_CONSENT_SUCCESS = 'POST_SAFETY_CONSENT_SUCCESS';
export const POST_SAFETY_CONSENT_FAILURE = 'POST_SAFETY_CONSENT_FAILURE';

export const UPLOAD_IMAGE_REQUEST = "UPLOAD_IMAGE_REQUEST"
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS"
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE"

export const GET_UPGRADE_PLANS = "GET_UPGRADE_PLANS"
export const GET_UPGRADE_PLANS_SUCCESS = "GET_UPGRADE_PLANS_SUCCESS"
export const GET_UPGRADE_PLANS_FAILURE = "GET_UPGRADE_PLANS_FAILURE"

export const GET_UPGRADE_PLANS_BY_ID = "GET_UPGRADE_PLAN_BY_ID"
export const GET_UPGRADE_PLANS_BY_ID_SUCCESS = "GET_UPGRADE_PLAN_BY_ID_SUCCESS"
export const GET_UPGRADE_PLANS_BY_ID_FAILURE = "GET_UPGRADE_PLAN_BY_ID_FAILURE"

export const UPDATE_HOBBIES_VALUES = "UPDATE_HOBBIES_VALUES"
export const UPDATE_PARTNER_PREF = "UPDATE_PARTNER_PREF"

export const FETCH_SAVESEARCH_DATA = "FETCH_SAVESEARCH_DATA"
export const FETCH_SAVESEARCH_DATA_SUCCESS = "FETCH_SAVESEARCH_DATA_SUCCESS"
export const FETCH_SAVESEARCH_DATA_FAILURE = "FETCH_SAVESEARCH_DATA_FAILURE"

export const POST_SAVESEARCH_DATA = "POST_SAVESEARCH_DATA"
export const POST_SAVESEARCH_DATA_SUCCESS = "POST_SAVESEARCH_DATA_SUCCESS"
export const POST_SAVESEARCH_DATA_FAILURE = "POST_SAVESEARCH_DATA_FAILURE"

export const DELETE_SAVESEARCH_DATA = "DELETE_SAVESEARCH_DATA"
export const DELETE_SAVESEARCH_DATA_SUCCESS = "DELETE_SAVESEARCH_DATA_SUCCESS"
export const DELETE_SAVESEARCH_DATA_FAILURE = "DELETE_SAVESEARCH_DATA_FAILURE"

export const POST_SPAM_REPORT_USER = "POST_SPAM_REPORT_USER"
export const POST_SPAM_REPORT_USER_SUCCESS = "POST_SPAM_REPORT_USER_SUCCESS"
export const POST_SPAM_REPORT_USER_FAILURE = "POST_SPAM_REPORT_USER_FAILURE"

export const VIEW_STORY_POST = "VIEW_STORY_POST"
export const VIEW_STORY_POST_SUCCESS = "VIEW_STORY_POST_SUCCESS"
export const VIEW_STORY_POST_FAILURE = "VIEW_STORY_POST_FAILURE"

export const GET_STORY_VIEWS_DETAILS = "GET_STORY_VIEWS_DETAILS"
export const GET_STORY_VIEWS_DETAILS_SUCCESS = "GET_STORY_VIEWS_DETAILS_SUCCESS"
export const GET_STORY_VIEWS_DETAILS_FAILURE = "GET_STORY_VIEWS_DETAILS_FAILURE"

export const GET_MATCH_SCORE = "GET_MATCH_SCORE"
export const GET_MATCH_SCORE_SUCCESS = "GET_MATCH_SCORE_SUCCESS"
export const GET_MATCH_SCORE_FAILURE = "GET_MATCH_SCORE_FAILURE"

export const UPDATE_DISPLAY_NAME = "UPDATE_DISPLAY_NAME"
export const UPDATE_DISPLAY_NAME_SUCCESS = "UPDATE_DISPLAY_NAME_SUCCESS"
export const UPDATE_DISPLAY_NAME_FAILURE = "UPDATE_DISPLAY_NAME_FAILURE"
export const UPDATE_DISPLAY_STATUS = "UPDATE_DISPLAY_STATUS"


export const SIGNUP_FIRST_STEP = "SIGNUP_FIRST_STEP"
export const SIGNUP_FIRST_STEP_SUCCESS = "SIGNUP_FIRST_STEP_SUCCESS"
export const SIGNUP_FIRST_STEP_FAILURE = "SIGNUP_FIRST_STEP_FAILURE"

export const SIGNUP_SECOND_STEP = "SIGNUP_SECOND_STEP"
export const SIGNUP_SECOND_STEP_SUCCESS = "SIGNUP_SECOND_STEP_SUCCESS"
export const SIGNUP_SECOND_STEP_FAILURE = "SIGNUP_SECOND_STEP_FAILURE"

export const SIGNUP_THIRD_STEP = "SIGNUP_THIRD_STEP"
export const SIGNUP_THIRD_STEP_SUCCESS = "SIGNUP_THIRD_STEP_SUCCESS"
export const SIGNUP_THIRD_STEP_FAILURE = "SIGNUP_THIRD_STEP_FAILURE"

export const RESET_STEPS = "RESET_STEPS"

export const RESEND_OTP = "RESEND_OTP"
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS"
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE"

export const RESET_EMAIL_PASSWORD_FIRST_STEP = "RESET_EMAIL_PASSWORD_FIRST_STEP"
export const RESET_EMAIL_PASSWORD_SUCCESS_FIRST_STEP = "RESET_EMAIL_PASSWORD_SUCCESS_FIRST_STEP"
export const RESET_EMAIL_PASSWORD_FAILURE_FIRST_STEP = "RESET_EMAIL_PASSWORD_FAILURE_FIRST_STEP"
export const RESET_EMAIL_PASSWORD_SECOND_STEP = "RESET_EMAIL_PASSWORD_SECOND_STEP"
export const RESET_EMAIL_PASSWORD_SUCCESS_SECOND_STEP = "RESET_EMAIL_PASSWORD_SUCCESS_SECOND_STEP"
export const RESET_EMAIL_PASSWORD_FAILURE_SECOND_STEP = "RESET_EMAIL_PASSWORD_FAILURE_SECOND_STEP"
export const RESET_EMAIL_PASSWORD_THIRD_STEP = "RESET_EMAIL_PASSWORD_THIRD_STEP"
export const RESET_EMAIL_PASSWORD_SUCCESS_THIRD_STEP = "RESET_EMAIL_PASSWORD_SUCCESS_THIRD_STEP"
export const RESET_EMAIL_PASSWORD_FAILURE_THIRD_STEP = "RESET_EMAIL_PASSWORD_FAILURE_THIRD_STEP"

export const RESET_PASSWORD_STEP = "RESET_PASSWORD_STEP"

